# Generated by Django 4.2.5 on 2024-01-22 17:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('featured_category', models.BooleanField(default=False, verbose_name='Featured Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.CharField(max_length=10, verbose_name='Service No.')),
                ('service_name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('service_description', ckeditor.fields.RichTextField(max_length=250, verbose_name='Service Description')),
                ('slug', models.SlugField(unique=True)),
                ('icon_for_homepage', models.ImageField(blank=True, upload_to='photos/services/', verbose_name='Icon for Homepage')),
                ('icon_for_services_page', models.ImageField(upload_to='photos/services/', verbose_name='Icon for Services Page')),
                ('service_heading', models.TextField(max_length=500, verbose_name='Service Heading')),
                ('service_image', models.ImageField(upload_to='photos/services/', verbose_name='Service Photo')),
                ('service_image_alt_text', models.CharField(max_length=150, verbose_name='Service Image Alt Text')),
                ('service_point_1_heading', models.CharField(blank=True, max_length=100, verbose_name='Service Point One')),
                ('service_point_1_description', models.TextField(blank=True, max_length=250, verbose_name='Point One Description')),
                ('service_point_2_heading', models.CharField(blank=True, max_length=100, verbose_name='Service Point Two')),
                ('service_point_2_description', models.TextField(blank=True, max_length=250, verbose_name='Point Two Description')),
                ('service_point_3_heading', models.CharField(blank=True, max_length=100, verbose_name='Service Point Three')),
                ('service_point_3_description', models.TextField(blank=True, max_length=250, verbose_name='Point Three Description')),
                ('service_point_4_heading', models.CharField(blank=True, max_length=100, verbose_name='Service Point Four')),
                ('service_point_4_description', models.TextField(blank=True, max_length=250, verbose_name='Point Four Description')),
                ('service_feature_1_heading', models.CharField(max_length=100, verbose_name='Service Feature One Heading')),
                ('service_feature_1_sub_heading', models.CharField(max_length=100, verbose_name='Feature One Sub-Heading')),
                ('service_feature_2_heading', models.CharField(max_length=100, verbose_name='Service Feature Two Heading')),
                ('service_feature_2_sub_heading', models.CharField(max_length=100, verbose_name='Feature Two Sub-Heading')),
                ('service_feature_3_heading', models.CharField(max_length=100, verbose_name='Service Feature Three Heading')),
                ('service_feature_3_sub_heading', models.CharField(max_length=100, verbose_name='Feature Three Sub-Heading')),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='Show on Homepage')),
                ('sub_menu', models.BooleanField(default=False, verbose_name='Enable Sub-Menu')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='photos/index_page/slider/', verbose_name='Slider Image')),
                ('slider_image_alt_text', models.CharField(max_length=150, verbose_name='Slider Image Alt Text')),
                ('title', models.CharField(max_length=250)),
                ('heading', models.TextField(max_length=500)),
                ('text', ckeditor.fields.RichTextField(max_length=500)),
                ('hire_us_btn', models.BooleanField(default=False, verbose_name='Enable Hire Us Button')),
            ],
            options={
                'verbose_name_plural': 'Index Slider',
            },
        ),
        migrations.CreateModel(
            name='SubServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.CharField(max_length=10, verbose_name='Service No.')),
                ('service_name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('service_description', ckeditor.fields.RichTextField(max_length=250, verbose_name='Service Description')),
                ('slug', models.SlugField(unique=True)),
                ('icon_for_services_page', models.ImageField(upload_to='photos/services/', verbose_name='Icon for Services Page')),
                ('service_heading', models.TextField(max_length=500, verbose_name='Service Heading')),
                ('service_image', models.ImageField(upload_to='photos/services/', verbose_name='Service Photo')),
                ('service_image_alt_text', models.CharField(max_length=150, verbose_name='Service Image Alt Text')),
                ('service_point_1_heading', models.CharField(blank=True, max_length=100, verbose_name='Service Point One')),
                ('service_point_1_description', models.TextField(blank=True, max_length=250, verbose_name='Point One Description')),
                ('service_point_2_heading', models.CharField(blank=True, max_length=100, verbose_name='Service Point Two')),
                ('service_point_2_description', models.TextField(blank=True, max_length=250, verbose_name='Point Two Description')),
                ('service_point_3_heading', models.CharField(blank=True, max_length=100, verbose_name='Service Point Three')),
                ('service_point_3_description', models.TextField(blank=True, max_length=250, verbose_name='Point Three Description')),
                ('service_point_4_heading', models.CharField(blank=True, max_length=100, verbose_name='Service Point Four')),
                ('service_point_4_description', models.TextField(blank=True, max_length=250, verbose_name='Point Four Description')),
                ('service_feature_1_heading', models.CharField(max_length=100, verbose_name='Service Feature One Heading')),
                ('service_feature_1_sub_heading', models.CharField(max_length=100, verbose_name='Feature One Sub-Heading')),
                ('service_feature_2_heading', models.CharField(max_length=100, verbose_name='Service Feature Two Heading')),
                ('service_feature_2_sub_heading', models.CharField(max_length=100, verbose_name='Feature Two Sub-Heading')),
                ('service_feature_3_heading', models.CharField(max_length=100, verbose_name='Service Feature Three Heading')),
                ('service_feature_3_sub_heading', models.CharField(max_length=100, verbose_name='Feature Three Sub-Heading')),
                ('sub_menu', models.BooleanField(default=False, verbose_name='Enable Sub-Menu')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add.services')),
            ],
            options={
                'verbose_name': 'Sub Service',
                'verbose_name_plural': 'Sub Services',
            },
        ),
        migrations.CreateModel(
            name='SubSubServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.CharField(max_length=10, verbose_name='Service No.')),
                ('service_name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('service_description', ckeditor.fields.RichTextField(max_length=250, verbose_name='Service Description')),
                ('slug', models.SlugField(unique=True)),
                ('icon_for_services_page', models.ImageField(upload_to='photos/services/', verbose_name='Icon for Services Page')),
                ('service_heading', models.TextField(max_length=500, verbose_name='Service Heading')),
                ('service_image', models.ImageField(upload_to='photos/services/', verbose_name='Service Photo')),
                ('service_image_alt_text', models.CharField(max_length=150, verbose_name='Service Image Alt Text')),
                ('service_point_1_heading', models.CharField(blank=True, max_length=100, verbose_name='Service Point One')),
                ('service_point_1_description', models.TextField(blank=True, max_length=250, verbose_name='Point One Description')),
                ('service_point_2_heading', models.CharField(blank=True, max_length=100, verbose_name='Service Point Two')),
                ('service_point_2_description', models.TextField(blank=True, max_length=250, verbose_name='Point Two Description')),
                ('service_point_3_heading', models.CharField(blank=True, max_length=100, verbose_name='Service Point Three')),
                ('service_point_3_description', models.TextField(blank=True, max_length=250, verbose_name='Point Three Description')),
                ('service_point_4_heading', models.CharField(blank=True, max_length=100, verbose_name='Service Point Four')),
                ('service_point_4_description', models.TextField(blank=True, max_length=250, verbose_name='Point Four Description')),
                ('service_feature_1_heading', models.CharField(max_length=100, verbose_name='Service Feature One Heading')),
                ('service_feature_1_sub_heading', models.CharField(max_length=100, verbose_name='Feature One Sub-Heading')),
                ('service_feature_2_heading', models.CharField(max_length=100, verbose_name='Service Feature Two Heading')),
                ('service_feature_2_sub_heading', models.CharField(max_length=100, verbose_name='Feature Two Sub-Heading')),
                ('service_feature_3_heading', models.CharField(max_length=100, verbose_name='Service Feature Three Heading')),
                ('service_feature_3_sub_heading', models.CharField(max_length=100, verbose_name='Feature Three Sub-Heading')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add.subservices')),
            ],
            options={
                'verbose_name': 'Sub-Sub Service',
                'verbose_name_plural': 'Sub-Sub Services',
            },
        ),
    ]
