# Generated by Django 4.2.5 on 2024-01-22 17:50

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=18)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('received_date', models.DateTimeField(auto_now_add=True, verbose_name='Received Date')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('photo', models.ImageField(upload_to='photos/team/')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('short_bio', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('about', ckeditor.fields.RichTextField(max_length=1500)),
                ('skill_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skill One')),
                ('skill_1_progress', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Skill One Progress')),
                ('skill_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skill Two')),
                ('skill_2_progress', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Skill Two Progress')),
                ('skill_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skill Three')),
                ('skill_3_progress', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Skill Three Progress')),
                ('skill_4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skill Four')),
                ('skill_4_progress', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Skill Four Progress')),
                ('skill_5', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skill Five')),
                ('skill_5_progress', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Skill Five Progress')),
                ('skill_6', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skill Six')),
                ('skill_6_progress', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Skill Six Progress')),
                ('skill_7', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skill Seven')),
                ('skill_7_progress', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Skill Seven Progress')),
                ('skill_8', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skill Eight')),
                ('skill_8_progress', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Skill Eight Progress')),
                ('skill_9', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skill Nine')),
                ('skill_9_progress', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Skill Nine Progress')),
                ('skill_10', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skill Ten')),
                ('skill_10_progress', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Skill ten Progress')),
                ('year_of_experience', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Year of Experience')),
                ('experience_1', models.TextField(blank=True, max_length=500, verbose_name='Experience One')),
                ('experience_2', models.TextField(blank=True, max_length=500, verbose_name='Experience Two')),
                ('experience_3', models.TextField(blank=True, max_length=500, verbose_name='Experience Three')),
                ('experience_4', models.TextField(blank=True, max_length=500, verbose_name='Experience Four')),
                ('experience_5', models.TextField(blank=True, max_length=500, verbose_name='Experience Five')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('other_website_font_awesome_icon', models.CharField(blank=True, max_length=100, verbose_name='Other Website Font Awesome Icon Class')),
                ('other_website_link', models.URLField(blank=True, verbose_name='Other Website Link')),
                ('active_status', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('photo', models.ImageField(upload_to='photos/testimonials/%y%m%d')),
                ('testimonial', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('project_description', ckeditor.fields.RichTextField(verbose_name='Project Description')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients_teams_projects.clients')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients_teams_projects.team', verbose_name='Associated Team Member')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
