# Generated by Django 4.2.5 on 2024-01-22 17:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('thumbnail', models.ImageField(upload_to='photos/blogs/%y/%m/%d')),
                ('thumbnail_alt_text', models.CharField(blank=True, max_length=150, verbose_name='Thumbnail Alt Text')),
                ('author_name', models.CharField(max_length=50, verbose_name='Author Name')),
                ('post', ckeditor.fields.RichTextField()),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
                ('show_on_slider', models.BooleanField(default=False, verbose_name='Show on Slider')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.posts')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
